### ISSUE TITLE
implement timeout

### ISSUE THREAD

**Issue by kedoska** [kedoska/go-zambra#1]
a step should define the `timeout`
```yaml
  - name: node
    args:
      - -e
      - "console.log('1st')"
    timeout: 1000ms
```
